---
title: "Zlaczenie JOIN"
author: "Jakub Sawczuk"
date: "4 05 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(spData)
library(sf)
library(dplyr)
library(ggplot2)
````

````{r}
dane1 <- st_read(dsn = 'J:/Desktop/ADP2020/ne_10m_populated_places.shp')

## Wczytujemy dane wektorowe dla powiatow
powiaty <- st_read(dsn = 'J:/Desktop/ADP2020/Jednostki_Administracyjne/Powiaty.shp')

## Wczytujemy dane z pliku excel
wynagrodzenia <- readxl::read_xlsx('J:/Desktop/ADP2020/Wynagrodzenia.xlsx', sheet = 2)

## Dodajemy do kodu w powiatach dodatkowe 0, zeby sie dlugosc znakow zgadzala z kodami z wynagrodzen
powiaty$JPT_KOD_JE <- paste0(powiaty$JPT_KOD_JE, '000')
````

```{r}

## Polaczenia DO POWIATOW dodajemy dane NIGDY ODWROTNIE !!!
polaczona <- powiaty %>% left_join(wynagrodzenia, 
                            by = c('JPT_KOD_JE'= 'Kod'))
```

```{r}
ggplot(polaczona, aes(fill=wynagrodzenia$Wartosc)) +
  geom_sf()
```

