---
title: "Zajęcia 2"
author: "Natalia Orzechowska"
date: "4 04 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(raster)
library(spData)
library(spDataLarge)
library(dplyr)
```

## Zadanie 1

Wyświetlcie mapę krajów Europejskich  wg liczby ludności


```{r}
plot(world[world$continent == "Europe", "pop"])
```

## Zadanie 2

Który kraj posiada najmniejszą liczbę ludności i ile wynosi?

```{r}
world %>% select(name_long,pop) %>% arrange(pop)%>% slice(0:1)
```

## Zadanie 3

```{r}
world %>% filter(continent == 'Asia') %>% count()
```
## Zadanie 4
Wyświetlcie histogram powierzchni  wszystkich niezależnych krajów (Sovereign Country)

```{r}
world %>% filter( type == "Sovereign country") %>% select(name_long, area_km2) %>% 
  ggplot(mapping = aes(x = name_long, y = area_km2))+geom_bar(stat = "identity", fill = "lightblue") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```
## Zadanie 5

Wyświetlcie wykres punktowy relacji pomiędzy lifeExp, a gdpPercap

```{r}
world %>% select(lifeExp, gdpPercap ) %>% ggplot(mapping = aes(x = lifeExp, y = gdpPercap)) + geom_point()
```

