---
title: "Zajecia2"
author: "adriannabukowska"
date: "4 04 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(raster)
library(spData)
library(dplyr)
library(ggplot2)
```


## Zadanie 1
Wyświetlcie mapę krajów Europejskich  wg liczby ludności
```{r}
world %>% 
  select(pop)%>%
  plot()

```

Który kraj posiada najmniejszą liczbę ludności i ile wynosi?
```{r}
world %>%
  select(pop,name_long)%>%
  arrange(pop) -> posortowane
head(posortowane,1)
```

Ile krajów znajduje się w Azji?
```{r}
world1=subset(world,continent == 'Asia')
nrow(world1)

```

Wyświetlcie histogram powierzchni  wszystkich niezależnych krajów (Sovereign Country)
```{r}
worldSloverign <- world %>%
filter(type == "Sovereign country")%>%
mutate(area_km2_mutate = area_km2 / 10000)
ggplot(worldSloverign, aes(x = area_km2_mutate)) +
geom_histogram(bins=50)

```

Wyświetlcie wykres punktowy relacji pomiędzy lifeExp, a gdpPercap
```{r}

ggplot(world, aes(x = lifeExp, y = gdpPercap)) +
geom_point()

```

