---
title: "Zajecia_2"
author: "JuliaDMichalska"
date: "4 04 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(sf)
library(raster)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(spData)
library(devtools)
library(fs)
```

## Zadanie 1
Wyświetlcie mapę krajów Europejskich wg liczby ludności

```{r}
plot(world[world$continent == 'Europe','pop'])
```

## Zadanie 2
Który kraj posiada najmniejszą liczbę ludności i ile wynosi?

```{r}
world %>%
  filter(pop == min(world$pop, na.rm=TRUE)) %>%
  select(c(pop, name_long)) %>%
  print()
```

## Zadanie 3
Ile krajów znajduje się w Azji?

```{r}
world %>%
  filter(continent == 'Asia') %>%
  summarise(n())
```

## Zadanie 4
Wyświetlcie histogram powierzchni wszystkich niezależnych krajów (Sovereign Country).

```{r}
world %>%
  filter(type == 'Sovereign country') %>%
  ggplot(aes(x = pop)) +
  geom_histogram()
```

## Zadanie 5
Wyświetlcie wykres punktowy relacji pomiędzy lifeExp, a gdpPercap.

```{r}
world %>%
  ggplot(aes(x = lifeExp, y = gdpPercap)) +
  geom_point()
```
