---
title: "Zajecia 2"
author: "Jakub Sawczuk"
date: "4 04 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## Zadanie 1:

Wyświetlcie mapę krajów Europejskich  wg liczby ludności

```{r }
# install.packages("fs")
# devtools::install_github("Nowosad/spDataLarge")

library(sf)
library(fs)
library(tidyverse)
library(ggplot2)
library(raster)
library(devtools)
library(spData)
library(dplyr)


world %>% dplyr::select(pop) %>% plot()

```

## Zadanie 2:
Który kraj posiada najmniejszą liczbę ludności i ile wynosi?
  
```{r }

world %>% dplyr::select(name_long,pop) %>% arrange(pop) %>% head(1)
  
```

## Zadanie 3:
Ile krajów znajduje się w Azji?

```{r }
world %>% dplyr::select(name_long,region_un) %>% filter(region_un == "Asia") %>% nrow
```


## Zadanie 4:
Wyświetlcie histogram powierzchni  wszystkich niezależnych krajów (Sovereign Country)

```{r }
world %>% dplyr::select(area_km2,name_long,continent,type) %>% filter(type == "Sovereign country") -> ramka
as_tibble(ramka)

ggplot(ramka, aes(x = area_km2)) +
  geom_histogram()
```


## Zadanie 5:
Wyświetlcie wykres punktowy relacji pomiędzy lifeExp, a gdpPercap

```{r }
ggplot(world, aes(x = lifeExp,y = gdpPercap)) +
  geom_point()
```
