---
title: "Zajecia 2"
author: "Jakub Sawczuk"
date: "4 04 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Zadanie 1:

Wyświetlcie mapę krajów Europejskich  wg liczby ludności

  ```{r }
library(sf)
library(raster)
library(spData)
library(tidyverse)
devtools::install_github("Nowosad/spDataLarge")
install.packages('spDataLarge', repos='https://nowosad.github.io/drat/', type='source')



install.packages("fs")
library(fs)
devtools::install_github("Nowosad/spDataLarge")

View(spDataLarge::shops)
names(world)
class(world)
plot(world)
summary(world)
summary(world["lifeExp"])
world_mini <- world[1:2, 1:3]
world_mini

world[world$continent == "Europe",'pop'] %>% plot()

world[world$continent == "Europe",c('name_long','pop')] -> populacja
populacja

  ```

## Zadanie 2:
Który kraj posiada najmniejszą liczbę ludności i ile wynosi?
  ```{r }
library(sf)
world %>% select(name_long,pop) %>% arrange(pop) -> kraje

  ```


Ile krajów znajduje się w Azji?
Wyświetlcie histogram powierzchni  wszystkich niezależnych krajów (Sovereign Country)
Wyświetlcie wykres punktowy relacji pomiędzy lifeExp, a gdpPercap

