---
title: "cw2"
output: html_document
---

```{r setup, include=FALSE}
library("sf")
library("raster")
library("spData")
library("spDataLarge")
library(dplyr)
library(ggplot2)
```

## Wyświetlcie mapę krajów Europejskich  wg liczby ludności
```{r}
world %>%
  filter(continent == "Europe") %>%
  select(pop) %>%
  plot()


world %>%
  filter(continent == "Europe") %>%
  select(pop) -> europe_pop

plot(europe_pop)
```


## Który kraj posiada najmniejszą liczbę ludności i ile wynosi?

```{r}
world %>%
  arrange(pop) %>%
  select(name_long,pop) %>%
  top_n(-10,wt=pop)
```


## Ile krajów znajduje się w Azji?

```{r}
world %>%
  filter(continent == "Asia") %>%
  count() 
```


## Wyświetlcie histogram powierzchni  wszystkich niezależnych krajów (Sovereign Country)

```{r}
world %>%
  filter(type == "Sovereign country") %>%
  ggplot(aes(area_km2)) +
  geom_histogram(bins = 150)
```


## Wyświetlcie wykres punktowy relacji pomiędzy lifeExp, a gdpPercap

```{r}
world %>%
  ggplot(aes(x = lifeExp, y = gdpPercap)) +
  geom_smooth()
```

