---
title: "Projekt zaliczeniowy"
author: Agnieszka Buszta, Magdalena Grzegorzewska
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(spData)
library(dplyr)
library(ggplot2)
library(sf)
library(plotly)
library(corrplot)
library(viridis)
```

## Projekt zaliczniowy
##Porównanie wynagrodzeń w latach 2003, 2004 i 2005. Celem jest zbadanie wpływu wejscia Polski do Uni Europejskiej. 

```{r}
powiaty <- st_read(dsn = 'j:/Documents/ADP2020/personal/magdalenagrzegorzewska/data/Powiaty.shp')

powiaty$JPT_KOD_JE <-paste0(powiaty$JPT_KOD_JE, '000')

wojewodztwa <- st_read(dsn = 'j:/Documents/ADP2020/personal/magdalenagrzegorzewska/data/Województwa.shp')

wojewodztwa$JPT_KOD_JE <-paste0(wojewodztwa$JPT_KOD_JE, '00000')

wynagrodzeniewojewodztwa <- readxl::read_xlsx('J:/Documents/ADP2020/personal/magdalenagrzegorzewska/data/wynagrodzeniewojewodztwa.xlsx')

wynagrodzenia <- readxl::read_xlsx('J:/Documents/ADP2020/personal/magdalenagrzegorzewska/data/wynagrodzenie.xlsx')
```



```{r pressure, echo=FALSE}
dane <- powiaty %>%
  left_join(wynagrodzenia, by = c('JPT_KOD_JE' = 'Kod')) 


dane %>%
  ggplot(aes(fill=`rok2003`, geometry=geometry)) +
  geom_sf() +
  labs(title = 'Wynagrodzenie przed wejściem Polski do UE')

dane %>%
  ggplot(aes(fill=`rok2004`, geometry=geometry)) +
  geom_sf() +
  labs(title = 'Wynagrodzenie na przełomie wejścia Polski do UE')

dane %>%
  ggplot(aes(fill=`rok2005`, geometry=geometry)) +
  geom_sf() +
  labs(title = 'Wynagrodzenie po wejściu Polski do UE')

```



```{r , echo=FALSE}
daneWojewodztwa <- wojewodztwa %>%
  left_join(wynagrodzenia, by = c('JPT_KOD_JE' = 'Kod')) 

map1 <- daneWojewodztwa %>%
  ggplot(aes(fill=`rok2003`, geometry=geometry)) +
  geom_sf() +
  labs(title = 'Wynagrodzenie 2003 przedstwaione na mapie wojewodztw')

map2 <- daneWojewodztwa %>%
  ggplot(aes(fill=`rok2004`, geometry=geometry)) +
  geom_sf() +
  labs(title = 'Wynagrodzenie 2004 przedstwaione na mapie wojewodztw')

map3 <- daneWojewodztwa %>%
  ggplot(aes(fill=`rok2005`, geometry=geometry)) +
  geom_sf() +
  labs(title = 'Wynagrodzenie 2005 przedstwaione na mapie wojewodztw')



```

## Podsumowanie wynagrodzenie w województwach


```{r , echo=FALSE}
Dane <-summary(wynagrodzeniewojewodztwa)
Dane
```

## Wykresy przedstwiające średnie wynagrodzenie w województwach w poszczególnych latach

```{r , echo=FALSE}
ggplot(wynagrodzeniewojewodztwa, aes(x = rok2003, y=Nazwa)) +
  geom_point() 

ggplot(wynagrodzeniewojewodztwa, aes(x = rok2004, y=Nazwa)) +
  geom_point() 

ggplot(wynagrodzeniewojewodztwa, aes(x = rok2005, y=Nazwa)) +
  geom_point() 

```

## Podsumowanie danych wynagrodzen w powiatach


```{r , echo=FALSE}
Dane <-summary(wynagrodzenia)
Dane

```

## Wzrost średnich wypłat

```{r , echo=FALSE}
wynagrodzeniewojewodztwa <- mutate(wynagrodzeniewojewodztwa,
                       roznica = rok2004 - rok2003)
wynagrodzeniewojewodztwa <- mutate(wynagrodzeniewojewodztwa,
                       roznica2 = rok2005 - rok2004)

wynagrodzeniewojewodztwa

```


## Kartogramy

```{r , echo=FALSE}

a <- tm_shape(daneWojewodztwa) + tm_fill(col = "JPT_NAZWA_")
b <- tm_shape(dane) + tm_fill(col = "JPT_NAZWA_")

tmap_arrange(a, b)

```

